# Task 4
Train classifiers for the GTSRB task

In [6]:
import numpy as np
import matplotlib.pyplot as plt
from simplelbp import local_binary_pattern
from traffic_signs import load_data
from traffic_signs import extract_lbp_features
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

### Extract Data

In [2]:
X, y = load_data(".")
F = extract_lbp_features(X)

Processing image 1/202
Processing image 2/202
Processing image 3/202
Processing image 4/202
Processing image 5/202
Processing image 6/202
Processing image 7/202
Processing image 8/202
Processing image 9/202
Processing image 10/202
Processing image 11/202
Processing image 12/202
Processing image 13/202
Processing image 14/202
Processing image 15/202
Processing image 16/202
Processing image 17/202
Processing image 18/202
Processing image 19/202
Processing image 20/202
Processing image 21/202
Processing image 22/202
Processing image 23/202
Processing image 24/202
Processing image 25/202
Processing image 26/202
Processing image 27/202
Processing image 28/202
Processing image 29/202
Processing image 30/202
Processing image 31/202
Processing image 32/202
Processing image 33/202
Processing image 34/202
Processing image 35/202
Processing image 36/202
Processing image 37/202
Processing image 38/202
Processing image 39/202
Processing image 40/202
Processing image 41/202
Processing image 42/202
P

### Test different Classifier
Evaluation of the performance with cross validation score

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [11]:
knn = KNeighborsClassifier()
lda = LinearDiscriminantAnalysis()
svm = SVC()
logreg = LogisticRegression()
classifiers = [knn, lda, svm, logreg]
for c in classifiers:
    acc = cross_val_score(c,F, y)
    print(acc)
    

[0.89705882 0.94117647 0.95454545]
[1.         0.95588235 0.98484848]
[0.54411765 0.58823529 0.53030303]
[1. 1. 1.]


C:\ProgramData\Anaconda3\envs\ml_tuni\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\envs\ml_tuni\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\envs\ml_tuni\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\envs\ml_tuni\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\ProgramData\Anaconda3\envs\ml_tuni\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables